// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.32.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// The type `SAKHA_DICT_NOVGORODOV` is not used by any `pub` functions, thus it is ignored.

String greet({required String name, dynamic hint}) =>
    RustLib.instance.api.greet(name: name, hint: hint);

String transliterateSakhaCyrillicToSakhaLatin(
        {required String text, dynamic hint}) =>
    RustLib.instance.api
        .transliterateSakhaCyrillicToSakhaLatin(text: text, hint: hint);
